# Generated by Django 3.0.3 on 2021-10-20 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedfileRequest',
            fields=[
                ('bedfile_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('pan_number', models.CharField(max_length=10)),
                ('date_requested', models.DateField()),
                ('requested_by', models.CharField(max_length=20)),
                ('request_status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.AutoField(primary_key=True, serialize=False)),
                ('ensembl_gene_id', models.CharField(max_length=15)),
                ('bedfile_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_maker.BedfileRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('ensembl_transcript_id', models.CharField(max_length=15)),
                ('RefSeq_transcript_id', models.CharField(max_length=15)),
                ('display_name', models.CharField(max_length=15)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('MANE_transcript', models.BooleanField()),
                ('bedfile_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_maker.BedfileRequest')),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_maker.Gene')),
            ],
        ),
    ]
