# Generated by Django 3.1.2 on 2021-09-28 13:25

import bed_maker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=bed_maker.models.get_default_profile_image, max_length=255, null=True, upload_to='')),
                ('hide_email', models.BooleanField(default=True)),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BedfileRequest',
            fields=[
                ('bedfile_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('pan_number', models.CharField(max_length=10)),
                ('date_requested', models.DateField()),
                ('requested_by', models.CharField(max_length=20)),
                ('requested_for', models.CharField(max_length=20)),
                ('request_status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], max_length=10)),
            ],
            options={
                'ordering': ('date_requested',),
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.AutoField(primary_key=True, serialize=False)),
                ('ensembl_gene_id', models.CharField(max_length=15)),
                ('bedfile_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_maker.bedfilerequest')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('ensembl_transcript_id', models.CharField(max_length=15)),
                ('RefSeq_transcript_id', models.CharField(max_length=15)),
                ('display_name', models.CharField(max_length=15)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('MANE_transcript', models.BooleanField()),
                ('bedfile_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_maker.bedfilerequest')),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_maker.gene')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('structure_id', models.AutoField(primary_key=True, serialize=False)),
                ('ensembl_structure_id', models.CharField(max_length=15)),
                ('structure_type', models.CharField(max_length=50)),
                ('version_number', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('chr_number', models.CharField(max_length=50)),
                ('DNA_strand', models.CharField(max_length=50)),
                ('bedfile_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_maker.bedfilerequest')),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_maker.gene')),
                ('transcript_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_maker.transcript')),
            ],
        ),
    ]
