# Generated by Django 3.1.2 on 2021-10-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='end_padded',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='start_padded',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
