# Generated by Django 3.1.2 on 2021-08-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bed_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='bedfile_request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_maker.bedfilerequest'),
        ),
    ]
