# Generated by Django 3.0.3 on 2022-03-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_maker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinvarCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_ensembl_id', models.CharField(max_length=15)),
                ('ensembl_transcript_version', models.CharField(default='', max_length=3)),
                ('clinvar_coverage_fraction', models.CharField(max_length=20)),
                ('clinvar_coverage_percentage', models.CharField(max_length=10)),
                ('clinvar_variants', models.CharField(max_length=50)),
            ],
        ),
    ]
