# Generated by Django 3.0.3 on 2022-04-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_maker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinvarCoverage_grch37',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_ensembl_id', models.CharField(max_length=15)),
                ('clinvar_coverage_fraction', models.CharField(max_length=20)),
                ('clinvar_variants', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClinvarCoverage_grch38',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_ensembl_id', models.CharField(max_length=15)),
                ('clinvar_coverage_fraction', models.CharField(default=None, max_length=20)),
                ('clinvar_variants', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='clinvar_coverage',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='clinvar_details',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='clinvar_variants',
        ),
        migrations.AlterField(
            model_name='transcript',
            name='coverage',
            field=models.CharField(max_length=50),
        ),
    ]
