# Generated by Django 3.1.2 on 2021-10-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_maker', '0002_auto_20211005_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='chr_number',
            new_name='exon_number',
        ),
        migrations.AddField(
            model_name='gene',
            name='chr_num',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcript',
            name='num_exons',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
