# Generated by Django 3.1.2 on 2021-08-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bed_maker', '0002_auto_20210820_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('ensembl_transcript_id', models.CharField(max_length=15)),
                ('RefSeq_transcript_id', models.CharField(max_length=15)),
                ('display_name', models.CharField(max_length=15)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('MANE_transcript', models.BooleanField()),
                ('bedfile_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_maker.bedfilerequest')),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_maker.gene')),
            ],
        ),
    ]
