# Generated by Django 3.0.3 on 2021-11-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_maker', '0002_auto_20211101_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='clinvar_details',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
