# Generated by Django 3.0.3 on 2022-03-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bed_maker', '0003_remove_clinvarcoverage_ensembl_transcript_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='clinvar_coverage',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='clinvar_details',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='clinvar_variants',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='coverage',
        ),
    ]
