# Generated by Django 3.0.3 on 2022-03-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bed_maker', '0004_auto_20220309_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinvarcoverage',
            name='clinvar_coverage_percentage',
        ),
    ]
