# Generated by Django 3.0.3 on 2022-03-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_maker', '0005_remove_clinvarcoverage_clinvar_coverage_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='coverage',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
